export default {
  title: "apietryga",
  author: "Antoni Pietryga",
  nav: {
    home: 'Home',
    projects: 'Projects',
    contact: 'Contact',
  },
  home: {
    title: "You found <b>Software Developer</b><br><b>which will do</b> the job",
    description: "I am self-taught programmer works with WEB and IoT projects,<br> additionally I teach web application programming",
    cta: "See my full experience",
    code: {
      title: "<b>Code</b> was my first <b>love</b>",
      description: "In 2010, I started Googling in order to create a game. Since then, web development has captured me completely.",
      cta: "see my code projects",
    },
    teaching: {
      title: "<b>Teaching</b> - the best way of <b>learning</b>",
      description: "I started my adventure with training with a computer skills course for seniors.",
      cta: "see my teach experience",
      reviews: {
        
        cta: "see reference",
        list: [
          { name: "ERNABO",
            img: "reviews/ernabo.svg",
            content: "Mr. Antoni causes change, commitment to work, responsibility and a large amount of patience",
            source: "/docs/1.pdf",
          },
          { name: "Fundacja Partycypacji Społecznej",
            img: "reviews/fundacja.svg",
            content: "Mr. Antoni not only implemented the program of classes, but also showed ingenuity - expanding the classes with original initiatives, which always enjoyed the satisfaction of the participants.",
            source: "/docs/6.pdf",
          },
          { name: "KUŹNIA EKSPERTÓW",
            img: "reviews/kuznia_ekspertow.svg",
            content: "Based on the cooperation so far, I certify that Mr. Antoni is worth recommending as a trainer.",
            source: "/docs/3.pdf",
          },
          { name: "OPS Krzyżanowice",
            img: "reviews/ops.svg",
            content: "Mr. Antoni proved to be a reliable, competent, professional person with a great sense of humor.",
            source: "/docs/5.pdf",
          },
          { name: "ERNABO",
            img: "reviews/ernabo.svg",
            content: "He is an ideal trainer who effectively transfers his extensive knowledge and additionally quickly wins the sympathy of his listeners.",
            source: "/docs/1.pdf",
          },
          { name: "Fundacja Partycypacji Społecznej",
            img: "reviews/fundacja.svg",
            content: "Mr. Antoni proved to be an extremely committed person with high qualifications and interpersonal skills.",
            source: "/docs/6.pdf",
          },
          { name: "KUŹNIA EKSPERTÓW",
            img: "reviews/kuznia_ekspertow.svg",
            content: "He performed his duties and responsibilities diligently. He was known as a meticulous and trustworthy person.",
            source: "/docs/3.pdf",
          },
          { name: "OPS Krzyżanowice",
            img: "reviews/ops.svg",
            content: "The meetings were held in an atmosphere of pleasant relaxation with a sense of effective acquisition of knowledge.",
            source: "/docs/5.pdf",
          },
          { name: "ERNABO",
            img: "reviews/ernabo.svg",
            content: "Classes are each time well thought out and properly prepared, in addition to theoretical knowledge, they are also characterized by a large number of examples of application in everyday life. ",
            source: "/docs/1.pdf",
          },
          { name: "Fundacja Partycypacji Społecznej",
            img: "reviews/fundacja.svg",
            content: "The trainings were conducted in a professional manner and each time they were highly appreciated by the participants, who also emphasized the very good atmosphere prevailing during the classes.",
            source: "/docs/6.pdf",
          },
          { name: "KUŹNIA EKSPERTÓW",
            img: "reviews/kuznia_ekspertow.svg",
            content: "He has extensive knowledge related to the subject of the training, he passes it on to the participants in a clear and understandable way.",
            source: "/docs/3.pdf",
          },
          { name: "ERNABO",
            img: "reviews/ernabo.svg",
            content: "Professional approach to participants by Mr. Antoni and his extensive knowledge of the subject of the training translates into its clear and understandable transmission",
            source: "/docs/1.pdf",
          },
          { name: "KUŹNIA EKSPERTÓW",
          img: "reviews/kuznia_ekspertow.svg",
          content: "He cares about both the group's accreditation and the substantive value of each meeting",
          source: "/docs/3.pdf",
          },
          { name: "OPS Krzyżanowice",
            img: "reviews/ops.svg",
            content: "The topics discussed during the training were presented in an innovative and interesting way, which significantly raised the level of awareness of the participants",
            source: "/docs/5.pdf",
          },

        ],
      },
    },
    business: {
      title: "<b>Business</b> is <b>business</b>",
      description: "In 2018, I started my first business, which resulted in some of the projects and a lot of experience featured on this page.",
      cta: "see my business projects",
    },
  },
  contact: {
    title: "Contact details",
    icons: {
      phone : "+48 732 012 715",
      mail: "antek.pietryga@gmail.com",
      messenger: "https://www.messenger.com/t/antoni.pietryga",
      instagram: "http://instagram.com/antek_pietryga",
      facebook: "https://www.facebook.com/antoni.pietryga/",
      youtube: "https://www.youtube.com/channel/UCB5bhBYgly7udyjyjj0K_UQ?view_as=subscriber",
      linkedin: "https://www.linkedin.com/in/apietryga/",
      github: "https://github.com/apietryga",
      stackoverflow: "https://stackoverflow.com/users/5252704/antek-pietryga",
    }
  },
  projects: {
    cta: "See ",
  },
}