export default {
  title: "apietryga",
  nav: {
    home: 'Home',
    projects: 'Projekty',
    contact: 'Kontakt',
  },
  home: {
    title: "hello <br> im apietryga",
    description: "Jestem samoukiem programowania, pracuję jako Software Developer. Najlepiej czuje się w Node i Nuxt. Tworzę projekty WEB i IoT. Prowadzę również szkolenia z programowania aplikacji internetowych. Chętnie porozmawiam o ciekawych projektach.",
    cta: "See my experience",
    code: {
      title: "<b>Kod</b> był moją pierwszą <b>miłością</b>",
      description: "W 2010 roku w celu stworzenia gry zacząłem googlować. Od tamtego czasu web development wciągnął mnie bez reszty."
    },
    teaching:{
      reviews:{
        // ! ORIGINALS
        // content: "Pana Antoniego cechuje sumienność, zaangażowanie do wykonywanej pracy, odpowiedzialność i duża doza cierpliwości, Dzięki otwartości i zdolności budowania dobrych relacji międzyludzkich, jest idealnym trenerem szkoleń skutecznie przekazującym swoją bogatą wiedzę i dodatkowo szybko zdobywającym sympatię słuchaczy.",
        // content: "Prowadzone przez p. Antoniego zajęcia są każdorazowo przemyślane i odpowiednio przygotowane, prócz wiedzy teoretycznej charakteryzują się również dużą ilością przykładów zastosowania w życiu codziennym. Dba on zarówno o aktywizację grupy, jak i dobre zrozumienie zagadnień przez uczestników.",
        // content: "Opierając się na dotychczasowej współpracy oraz profesjonalnym podejściu do uczestników pana Antoniego oraz jego bogatej wiedzy z tematyką szkolenia, co przekłada się na jej jasne i zrozumiałe przekazywanie, z przyjemnością polecam pana Antoniego Pietryga jako rzetelnego trenera i sam chętnie kontynuował będę współpracę z p. Antonim w przyszłości.",
        // content: "Pan Antoni Pietryga charakteryzuje się profesjonalnym podejściem do uczestników szkolenia i powierzonego zadania. Posiada bogatą wiedzę związaną z tematyką szkolenia, w sposób jasny i zrozumiały przekazuje ją uczestnikom zajęć. Dba zarówno o akrywizację grupy, jak i wartość merytoryczną każdego spotkania",
        // content: "W oparciu o dotychczasową współpracę zaświadczam, że Pan Antoni Pietryga jest godny polecenia jako trener. Rzetelnie wywiązał się z nałożonych na niego zadań i obowiązków. Dał się poznać jako osoba skrupulatna i warta zaufania.",
        // content: "Pan Antoni nie tylko realizował program zajęć, ale również wykazał się pomysłowością - poszerzając zajęcia o autorskie inicjatywy, któe zawsze cieszyły się zadowoloeniem uczestników. Z pełnym przekonaniem polecam Pana Antoniego Pietryga jako efektywnego szkoleniowca, który zapewni wysoki poziom prowadzonych zajęć.",
        // content: "Pan Antoni Pietryga dał się poznać jako osoba niezwykle zaangażowana, o wysokich kwalifikacjach oraz umiejętnościach interpersonalych. Szkolenia prowadzone zostały w sposób profesjonalny i każdorazowo wysoko oceniane przez uczestników, którzy podkreślali rówież bardzo dobrą atmosferę panującą na zajęciach.",
        list: [
          { name: "ERNABO",
            img: "reviews/ernabo.svg",
            content: "Pana Antoniego cechuje sumienność, zaangażowanie do wykonywanej pracy, odpowiedzialność i duża doza cierpliwości",
            source: "/docs/1.pdf",
          },
          { name: "ERNABO",
            img: "reviews/ernabo.svg",
            content: "Dzięki otwartości i zdolności budowania dobrych relacji międzyludzkich, jest idealnym trenerem szkoleń skutecznie przekazującym swoją bogatą wiedzę i dodatkowo szybko zdobywającym sympatię słuchaczy.",
            source: "/docs/1.pdf",
          },
          { name: "ERNABO",
            img: "reviews/ernabo.svg",
            content: "Zajęcia są każdorazowo przemyślane i odpowiednio przygotowane, prócz wiedzy teoretycznej charakteryzują się również dużą ilością przykładów zastosowania w życiu codziennym. Dba on zarówno o aktywizację grupy, jak i dobre zrozumienie zagadnień przez uczestników.",
            source: "/docs/1.pdf",
          },
          { name: "ERNABO",
            img: "reviews/ernabo.svg",
            content: "Profesjonalne podejście do uczestników przez pana Antoniego oraz jego bogata wiedzy z tematyki szkolenia, przekłada się na jej jasne i zrozumiałe przekazywanie",
            source: "/docs/1.pdf",
          },
          { name: "KUŹNIA EKSPERTÓW",
            img: "reviews/kuznia_ekspertow.svg",
            content: "Posiada bogatą wiedzę związaną z tematyką szkolenia, w sposób jasny i zrozumiały przekazuje ją uczestnikom zajęć. Dba zarówno o akrywizację grupy, jak i wartość merytoryczną każdego spotkania",
            source: "/docs/3.pdf",
          },
          { name: "KUŹNIA EKSPERTÓW",
            img: "reviews/kuznia_ekspertow.svg",
            content: "W oparciu o dotychczasową współpracę zaświadczam, że Pan Antoni Pietryga jest godny polecenia jako trener. Rzetelnie wywiązał się z nałożonych na niego zadań i obowiązków. Dał się poznać jako osoba skrupulatna i warta zaufania.",
            source: "/docs/3.pdf",
          },
          { name: "Fundacja Partycypacji Społecznej",
            img: "reviews/fundacja.svg",
            content: "Pan Antoni nie tylko realizował program zajęć, ale również wykazał się pomysłowością - poszerzając zajęcia o autorskie inicjatywy, które zawsze cieszyły się zadowoloeniem uczestników.",
            source: "/docs/6.pdf",
          },
          { name: "Fundacja Partycypacji Społecznej",
            img: "reviews/fundacja.svg",
            content: "Pan Antoni Pietryga dał się poznać jako osoba niezwykle zaangażowana, o wysokich kwalifikacjach oraz umiejętnościach interpersonalych.",
            source: "/docs/6.pdf",
          },
          { name: "Fundacja Partycypacji Społecznej",
            img: "reviews/fundacja.svg",
            content: "Szkolenia prowadzone zostały w sposób profesjonalny i każdorazowo wysoko oceniane przez uczestników, którzy podkreślali rówież bardzo dobrą atmosferę panującą na zajęciach.",
            source: "/docs/6.pdf",
          },
          
          { name: "OPS Krzyżanowice",
            img: "reviews/ops.svg",
            content: "Pan Antoni dał się poznać jako osoba rzetelna, kompetentna, fachowa, z ogromnym poczuciem humoru, dzięki czemu spotkania przebiegały w atmosferze przyjemnego relaksu z jednoczesnym poczuciem efektywnego pozyskania wiedzy.",
            source: "/docs/1.pdf",
          },
          { name: "OPS Krzyżanowice",
            img: "reviews/ops.svg",
            content: "Tematy omawiane podczas szkolenia zostały ujeęctye w nowatorski i interesuj ący sposób, przez co zacząco podniosły poziom świadomości uczestników",
            source: "/docs/1.pdf",
          },
        ],
      }
    }

  },
  

}